server.port=8091
spring.application.name=ms-paquetes

spring.datasource.url=jdbc:mariadb://localhost:3306/db_ms_paquetes
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

logging.level.com.sivebo=DEBUG